### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by luzianscherrer** [mattleibow/Socket.IO.Client#1]
I've tried installing this package but I get the following error:

Could not install package 'Square.OkIO 1.5.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Am I missing something?

I'm running Windows 10 Pro and Visual Studio 2015 with .NET Framework 4.6.

**Comment by mattleibow** [comment]
HI @luzianscherrer Are you trying to install the component into an Android class library? This library only works with Android. It is a Xamarin.Android binding for the Java/Android library.  For a normal, or in your case, a portable library, use [SocketIoDotNet](http://bit.ly/1PpUPSv). SocketIoDotNet should work for all platform types, even the Xamarin ones.

**Comment by luzianscherrer** [comment]
Thanks for getting back to me. The project that I'm working on is a Xamarin "Shared Asset Project" using Android and Windows Phone as target platforms. But I have now switch to SocketIoDotNet in the meantime and that works. You can close the issue.

**Comment by GnanaprakashChandiran** [comment]
i need to install socket into pcl.
