### ISSUE TITLE
Add iOS Support

### ISSUE THREAD

**Issue by josephkandi** [mattleibow/Socket.IO.Client#5]
The library only works for Android, it would be nice to have it work for iOS as well. Here is a guy with the SocketIO for IOS but he uses his own namespacing, https://github.com/Quobject/SocketIoClientDotNet/, i would keep using the same namespacing as the official one

**Comment by mattleibow** [comment]
This repository is just for the binding of the official Android packages. Unless they create an Objective-C library, I can't really do much.
